version: '3.1'

services:
  db:
    image: mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: maple-guild
      MYSQL_USER: user
      MYSQL_PASSWORD: 123123
    volumes:
      - db_data:/var/lib/mysql
      - ./e2e/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data: